### ISSUE TITLE
Need to specify extra_link_args to compile

### ISSUE THREAD

**Issue by ahwillia** [PythonOT/POT#113]
Hi, just wanted to mention that I needed to add **`extra_link_args=["-stdlib=libc++"]`** inside **`ext_modules = cythonize(Extension( ... ))`** to get the cython code to compile. I'm using Python 3.7 on Mojave 10.14.4 with...

```
$ gcc --version

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Getting these things to compile is always tricky for me. Let me know if you want more info.

**Comment by rflamary** [comment]
thank you for the feedback.

We will look into it and maybe add the arguments fro macosx. in setup.py

**Comment by rflamary** [comment]
This should work since PR #130
