### ISSUE TITLE
getting 'std::length_error' when running pot.emd

### ISSUE THREAD

**Issue by sztankatt** [PythonOT/POT#117]
I have a matrix M (50k by 50k) of distances (each distance between 0 and 1), and when running `ot.emd([], [], M)` I get the following error:

```sh
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted
```

What could cause this? The same code works for smaller matrices ie 10k by 10k or 15k by 15k

**Comment by rflamary** [comment]
Hello @sztankatt 

The error is probably due to a memory problem (the memory allocation fails).

Note that due to the architecture of the C++ solver we need to copy i memory the cost matrix which can fail if the memory cannot fit the copy.

**Comment by sztankatt** [comment]
Hi @rflamary! Thanks for the reply. I am running the code on a big server (1.5TB memory), so should have enough memory.

Could it be that somehow in my python code I mess up the memory allocation of C++?

Otherwise, I have no idea how to fix this...

**Comment by sztankatt** [comment]
Hi @rflamary! So my code is literally this:

```python
>>> import numpy as np
>>> import ot
>>> M = np.load('test.npy')
>>> np.shape(M)
(62332, 53526)
>>> M
array([[1.40118821e-05, 1.71256336e-05, 1.40118821e-05, ...,
        1.24550063e-05, 1.40118821e-05, 1.40118821e-05],
       [1.71256336e-05, 9.34125472e-06, 1.86825094e-05, ...,
        1.08981305e-05, 1.55687579e-05, 1.55687579e-05],
       [1.55687579e-05, 1.08981305e-05, 1.24550063e-05, ...,
        1.40118821e-05, 1.40118821e-05, 1.71256336e-05],
       ...,
       [1.86825094e-05, 1.24550063e-05, 1.40118821e-05, ...,
        1.40118821e-05, 1.55687579e-05, 1.86825094e-05],
       [1.71256336e-05, 7.78437893e-06, 1.55687579e-05, ...,
        1.24550063e-05, 1.08981305e-05, 1.24550063e-05],
       [1.24550063e-05, 1.55687579e-05, 1.40118821e-05, ...,
        1.71256336e-05, 1.08981305e-05, 1.24550063e-05]])
>>> M.dtype
dtype('float64')
>>> ot.emd([], [], M)
```

and then I get immediately the error:

```sh
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted
```

**Comment by rflamary** [comment]
Humm, it's hard to know, if it comes from the underlying C++ code it's hard to find the erreor.  Could you try and find at which size of problem things explode? I recall running it on 50kx50k with some tinkerring of nitermax.

Aslo try giving the emd functions some proper weights from ot.unif . It is probably not the problem but it's worth trying.

**Comment by mnmjh1215** [comment]
Any update on this error?
I'm experiencing the same problem with matrix of size approximately 20k x 120k when running pot.emd.

**Comment by rflamary** [comment]
Hello we recently merged a new cleaned up implementation for the c++ solver, could you install/copile the master version of POT nd tell us if you still have this problem (it should be fixed we put all index in int64) ?

**Comment by rflamary** [comment]
We have solved EMD problems of size 150kx150k  with version 0.8 so I'm closing this issue
