### ISSUE TITLE
`setup.py clean` cythonizes file and leaves directory unclean

### ISSUE THREAD

**Issue by gspr** [PythonOT/POT#122]
**Describe the bug**
Calling `setup.py` with `clean` as argument should clean up the build directories. However, it currently causes the cythonization of `ot/lp/emd_wrap.pyx`, leaving the build directory unclean. This is a problem for downstream distributions.

**To Reproduce**
1. Check out a clean copy of the code.
2. Observe there is no `ot/lp/emd_wrap.cpp`.
3. Run `python3 setup.py clean`.

**Expected behavior**
A clean build directory.

**Actual outcome**
```
$ python3 setup.py clean
Compiling ot/lp/emd_wrap.pyx because it changed.
[1/1] Cythonizing ot/lp/emd_wrap.pyx
/usr/lib/python3/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/gspr/tmp/POT/ot/lp/emd_wrap.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running clean

$ head -n 1 ot/lp/emd_wrap.cpp
/* Generated by Cython 0.29.14 */
```
 - OS: Debian 11 (Testing)
 - Python version: 3.7.6
- How was POT installed: source, both 1b58440457b25aace9dac56aa21144286e60f16e and 0.6.0 were tested

**Comment by rflamary** [comment]
Hello,

Thank you for the detailed report. I can see how this is a problem for distributions. We could add the cleanup of cythonized files in `make clean` or we could also add a manual removing as a test in setup.py with something similar to
http://nfoti.github.io/a-creative-blog-name/posts/2013/02/07/cleaning-cython-build-files/

or
https://github.com/bjodah/pyodeint/blob/98b806aa0a330e0cea91be950de0b110fa64a5ed/setup.py#L25

If you want to contribute it your are welcome or we will get around to it when we find time.

**Comment by rflamary** [comment]
This has been updated un PR #143 the .cpp file should be deleted when calling setup.py with clean
