### ISSUE TITLE
barycenter_sinkhorn possible mistake

### ISSUE THREAD

**Issue by FerdinandGns** [PythonOT/POT#134]
Hello everyone,
It seems that there is a mistake in ot/bregman.py for the following function:
barycenter_sinkhorn
line 1123 : u = (geometricMean(UKv) / UKv.T).T
geometricMean(UKv) should be replaced by geometricBar(UKv, weights)  if we do as in: https://github.com/gpeyre/2014-SISC-BregmanOT/tree/master/code/barycenters
(I tested with Gaussians, and it seems that I am correct)

Best regards

**Comment by rflamary** [comment]
Seems you are right, Good catch!

It is just the initialization (we use the geometricBar in the loop) . If you want you can do a PR. Or else we will fix it in the near future. Thank you.

**Comment by rflamary** [comment]
This has een closed in PR #195
