### ISSUE TITLE
batch calculations

### ISSUE THREAD

**Issue by AdrienCorenflos** [PythonOT/POT#161]
Hi,

It would be nice (if not necessary for heavy-lifting purposes) to allow batching in all functions. I think it wouldn't come at a hefty price thanks to the ellipsis slice syntax (i.e. arr[..., -2]).

For example the 1D EMD can be vectorized and made batch compatible using the syntax below (written in tensorflow for my own purposes as I was implementing a sliced wasserstein - but the code is very numpy-like). In the below snippet, emd is taken across the last trailing dimension it means that all dimensions except the last have to be equal. This doesn't return the batched transportation plan but you get the gist. Also note that this allows to make full use of GPUs and especially TPUs as I have written everything in native tensorflow.

```python
import ot
import tensorflow as tf

@tf.function
def sqeuclidean(x, y):
    return (x-y)**2

@tf.function
def emd_1d(w_x, w_y, x, y, metric):
    n_batch_dim = len(x.shape) - 1

    all_values = tf.concat([x, y], -1)
    all_weights = tf.concat([w_x, w_y], -1)
    factor = tf.concat([tf.zeros_like(w_x), tf.ones_like(w_y)], -1)

    all_values_index = tf.argsort(all_values, -1)
    sorted_values = tf.gather(all_values, all_values_index, batch_dims=n_batch_dim)
    sorted_weights = tf.gather(all_weights, all_values_index, batch_dims=n_batch_dim)
    sorted_mask = tf.gather(factor, all_values_index, batch_dims=n_batch_dim)

    cdf_y = tf.math.cumsum(sorted_mask * sorted_weights, -1)[..., :-1]
    cdf_x = tf.math.cumsum((1. - sorted_mask) * sorted_weights, -1)[..., :-1]

    delta = sorted_values[..., 1:] - sorted_values[..., :-1]
    integrand = metric(cdf_y, cdf_x) * delta

    return tf.reduce_sum(integrand, -1)

B = 2
N = 10
D = 150

w_x = tf.random.uniform([B, N, D], 0., 1.) ** 2
w_x = w_x / tf.reduce_sum(w_x, axis=-1, keepdims=True)

w_y = tf.ones([B, M, D])
w_y = w_y / tf.reduce_sum(w_y, axis=-1, keepdims=True)

x = tf.random.uniform([B, N, D], -1., 1.)
y = tf.random.uniform([B, M, D], -1., 1.)

np_x = x[0, 0].numpy()
np_y = y[0, 0].numpy()
np_w_x = w_x[0, 0].numpy()
np_w_y = w_y [0, 0].numpy()

batched_res = emd_1d(w_x, w_y, x, y, sqeuclidean)
res = ot.lp.emd2_1d(np_x, np_y, w_x, w_y, metric='sqeuclidean')

assert res == batched_res[0, 0].numpy()
```

**Comment by rflamary** [comment]
I'm closing this issue, the function `ot.wasserstein_1d` has been merged and is performing batch computations on backends.

https://pythonot.github.io/all.html?highlight=wasserstein_1d
