### ISSUE TITLE
POT Slack channel

### ISSUE THREAD

**Issue by undefdev** [PythonOT/POT#177]
Hi!

In the readme it says that one can ask questions on the POT Slack channel,
however it seems I can't create an account without a @unice.fr email address (which I don't have).

So I suppose either the readme should be adjusted, or access to non @unice.fr addresses should be granted.

Thanks!

**Comment by agramfort** [comment]
I would btw suggest to user gitter.im for this.

my 2c

**Comment by rflamary** [comment]
Hello sorry about that you should be able to join now with your email. Feel free to contact us on the slack now!

About gitter.im I just created a community but I can't promise I will be there as often as slack that I use everydays:
https://gitter.im/PythonOT/community#

Rémi

**Comment by ucalyptus** [comment]
@rflamary can you point me to the slack invite link, I just have the url .
