### ISSUE TITLE
Unexpected result from lp.barycenter for 1d distributions

### ISSUE THREAD

**Issue by devmessias** [PythonOT/POT#179]
Hi. 
I’m studying optimal transport. Therefore, I don’t know if it’s really a bug or if I just misunderstood some concept.

The barycenter of N normal distributions, ![image](https://user-images.githubusercontent.com/6979335/82131737-c72de980-97ae-11ea-8182-9b9a655f3188.png), is a normal distribution ![image](https://user-images.githubusercontent.com/6979335/82131751-e0369a80-97ae-11ea-82ad-f4de7dffadec.png)
where ![image](https://user-images.githubusercontent.com/6979335/82131610-5508d500-97ad-11ea-881c-8d9f88c52438.png) and ![image](https://user-images.githubusercontent.com/6979335/82131602-3c98ba80-97ad-11ea-8cef-4838dd3421b9.png).

Therefore, for 1d distributions, with the following parameters
![image](https://user-images.githubusercontent.com/6979335/82131612-5cc87980-97ad-11ea-9446-639b69899ffa.png)
and using uniform weights the barycenter is ![image](https://user-images.githubusercontent.com/6979335/82131837-e1b49280-97af-11ea-9b84-fa6edf8ebc68.png).  However, using the ```op.lp.barycenter```  I obtained a very different result.

```python
import ot
import numpy as np
import scipy.spatial
from ot.datasets import make_1D_gauss as gauss
import matplotlib.pyplot as plt

np.random.seed(1)
nbins = 100
bins = np.linspace(-6, 6, nbins)

p1 =  np.random.normal(-2, 1, size=100000)
p2 =  np.random.normal(2, 1, size=100000)
pExpected =  np.random.normal(0, 1, size=100000)

w1, edges = np.histogram(p1, bins=bins, density=True)
w2, edges = np.histogram(p2, bins=bins, density=True)
baryExpected, edges = np.histogram(pExpected, bins=bins, density=True)

w1 /= w1.sum()
w2 /= w2.sum()

baryExpected /= baryExpected.sum()

xs = np.diff(bins)/2 + edges[0:nbins-1]
M = scipy.spatial.distance.cdist(xs.reshape(nbins-1,1), xs.reshape(nbins-1,1))

M /= M.max()

A = np.array([w1, w2]).T

bary_wass = ot.lp.barycenter(A, M,   np.array([1/2., 1/2.]))
#reg = 1e-3
#bary_wass = ot.bregman.barycenter(A, M, reg, np.array([1/2., 1/2.]))
plt.plot(xs, w1, c="b")
plt.plot(xs, w2, c="g")
plt.plot(xs, baryExpected, c="black")
plt.plot(xs, bary_wass, c="r", linestyle="--")
plt.legend(["N_1", "N_2", "Expected", "LP"])
plt.show()
```

![image](https://user-images.githubusercontent.com/6979335/82132278-8b961e00-97b4-11ea-9241-4c90ae2d1b9c.png)
```python
mExpected = (ot.emd2_1d(baryExpected, w1) + ot.emd2_1d(baryExpected, w2))/2.
mObtained = (ot.emd2_1d(bary_wass, w1)+ot.emd2_1d(bary_wass, w2))/2.
mExpected, mObtained
```
```bash
(3.324831296576947e-07, 0.00011103021311330773)
```

**Comment by hichamjanati** [comment]
That's because the barycenter of Gaussians is Gaussian for the *squared* euclidean distance. 
Adding `M = M ** 2` fixes this
<img width="574" alt="Screenshot 2020-05-17 at 01 09 16" src="https://user-images.githubusercontent.com/17051500/82133382-cc5d5980-97eb-11ea-977f-eb1e9db1bb54.png">

**Comment by devmessias** [comment]
Thanks @hichamjanati !
