### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by ayushkarnawat** [PythonOT/POT#180]
I think it is useful to add a PR template, so that it streamlines how PRs are made and ensures that the user has fulfilled all the requirements. I think the one used by [nevergrad](https://github.com/facebookresearch/nevergrad/blob/master/.github/PULL_REQUEST_TEMPLATE.md) is a good starting point. 

Additionally, I think it also makes sense to move `contributing.md` and `code_of_conduct.md` to `.github/` folder. Finally, it may also be worth looking into supporting (a) how to ask questions and (b) feature requests within an issue template.

I can start a PR, if people agree.

**Comment by rflamary** [comment]
That is a good idea. I began working on it a while ago but never got around to do it properly. the template from nevergrad is nice. 

I agree that there should also be templates/choice for issues for feature requests. 

For questions i think we should be more clear that they should use the mailing list or slack or even contact us on gitter as you did. The github issues are not place for questions unless they are about a bug.

i'm OK with moving the contributing and code of conduct within .gihtub

**Comment by ayushkarnawat** [comment]
> For questions i think we should be more clear that they should use the mailing list or slack or even contact us on gitter as you did. The github issues are not place for questions unless they are about a bug.

Yes, I don't know if this is really a problem or actually beneficial. 

For one, having more options allows someone who doesn't want to sign up for a service (i.e. slack) to use another one (i.e. mailing list) to ask questions/comments. 

On the other hand, this means that all questions/comments are jumbled across different sources, which might not be good for scalability (i.e. duplicate questions would be reposted on different channels rather than referring to one of the previously asked ones). A fix for this would be to use one forum for all questions/comments/concerns, i.e. something like `discuss.pythonot.org` (I'm thinking something similar to [discuss.pytorch.org](https://discuss.pytorch.org)).  The only issue, however, is that this maybe take some time to setup properly, and idk if that would be premature optimization (in some sense).

> I agree that there should also be templates/choice for issues for feature requests.

How is [this](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/ISSUE_TEMPLATE/feature_request.md) feature request template used by PytorchLightning? It also might be a good starting point to model ours after.

**Comment by rflamary** [comment]
OK. I'm on slack regularly, Gitter more rarely but I always answer to question on the mailing list (even if they are rare). So i'm for leaving the options ;)

POT is clearly not big enough to justify a forum. Note that we have a FAQ in the getting started section of the documentation and we should complete it with questions and answers for regular ones.

Feature template is great.
