### ISSUE TITLE
line_search_armijo returns alpha > 1

### ISSUE THREAD

**Issue by octavian-ganea** [PythonOT/POT#184]
line_search_armijo can return alpha > 1 because that's what the scipy function was doing. However, this affects the cg() function used in both GW and FGW functions and returns transport plans with negative entries when armijo=True.

**Comment by rflamary** [comment]
This is indeed a problem. 

If you want to do a PR to handle this case (basically return min(1,alpha)) you are welcome. Else we will get around to it in the following days.

**Comment by rflamary** [comment]
Closed in #189
