### ISSUE TITLE
I get some errors when I use  ot.da.SinkhornLpl1Transport function

### ISSUE THREAD

**Issue by BX-xb** [PythonOT/POT#194]
## Describe the bug
Hello everyone!
I get some errors when I use  ot.da.SinkhornLpl1Transport function:
ot_lpl1 = ot.da.SinkhornLpl1Transport(reg_e=1e-1, reg_cl=1e0)
ot_lpl1.fit(Xs=train, ys=Class_train, Xt=Test)
transp_Xs_lpl1 = ot_lpl1.transform(Xs=train)
Then some errors occure:
Warning: numerical errors at iteration 0
C:\Anaconda\envs\tensorflow\lib\site-packages\ot\bregman.py:363: RuntimeWarning: divide by zero encountered in true_divide
  v = np.divide(b, KtransposeU)
C:\Anaconda\envs\tensorflow\lib\site-packages\ot\bregman.py:364: RuntimeWarning: divide by zero encountered in true_divide
  u = 1. / np.dot(Kp, v)

**Comment by rflamary** [comment]
Hello,

This warning means that there is numerical problems because the K matrix is too small. You should use a larger entropic regularization to avoid that. We should provide  a better warning message and will work on that in the future.

**Comment by BX-xb** [comment]
Thank you
