### ISSUE TITLE
How can I use OT on 3 dimension points?

### ISSUE THREAD

**Issue by MurielCuiCui** [PythonOT/POT#197]

**Comment by rflamary** [comment]
You can use OT on 3D samples.

The examples on images for color transfer actually work in 3D see:
https://pythonot.github.io/auto_examples/domain-adaptation/plot_otda_color_images.html#sphx-glr-auto-examples-domain-adaptation-plot-otda-color-images-py

**Comment by caiquanyou** [comment]
How could I use OT between three  probability distributions and may get the return array like shape of (x,y,z)?
