### ISSUE TITLE
line_search_armijo throws exception

### ISSUE THREAD

**Issue by panpan2** [PythonOT/POT#198]
## Describe the bug
scipy.optimize.linesearch.scalar_search_armijo can return `alpha=None`. In optim.py:line_search_armijo as part of a previous issue [https://github.com/PythonOT/POT/issues/184](https://github.com/PythonOT/POT/issues/184), we restrict the value of `alpha` to be at most 1 with `min(1, alpha)` but this throws an Exception when `alpha` is `None`.

### Expected behavior
Return `None` instead of throwing an Exception

Output of the following code snippet:
```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import ot; print("POT", ot.__version__)

'''
Darwin-19.2.0-x86_64-i386-64bit
Python 3.7.7 (default, May  6 2020, 04:59:01)
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.18.1
SciPy 1.2.1
POT 0.7.0
'''
```

### Additional context

https://github.com/PythonOT/POT/blob/acfff525e043c8733936e8e99367543edd28822b/ot/optim.py#L72

**Comment by rflamary** [comment]
Closed in #199
