### ISSUE TITLE
2D Optimal transport for different metrics

### ISSUE THREAD

**Issue by mzprose** [PythonOT/POT#247]
https://pythonot.github.io/auto_examples/plot_OT_L1_vs_L2.html
Such as '2D Optimal transport for different metrics',

xs[:, 0] = np.arange(n) + 1
xs[:, 1] = (np.arange(n) + 1) * -0.001  # to make it strictly convex...

xt = np.zeros((n, 2))
xt[:, 1] = np.arange(n) + 1

a, b = ot.unif(n), ot.unif(n)  # uniform distribution on samples

I want to know when calculating, I have two numpy matrices, and now I want to calculate emd distance.
What does a,b, mean, what does xs,xt mean, and how do I define them?

**Comment by rflamary** [comment]
you should look at this example that compute the OT for matrices of samples:

https://pythonot.github.io/auto_examples/plot_OT_2D_samples.html#compute-emd

If you are interested by the value of teh EMD then you should use ot.emd2 function insteda of ot.emd.

**Comment by mzprose** [comment]
Thank you for your reply, I will try
