### ISSUE TITLE
Sliced Wasserstein Distance

### ISSUE THREAD

**Issue by arijitthegame** [PythonOT/POT#261]
Hi all, 

 Thank you for such a wonderful package. I just installed the latest version of POT. And I am trying to use the sliced Wasserstein distance as in the example. 

    import ot
    def compute_sliced_wass(source_dist, target_dist, weights='uniform', n_seed=42, n_proj = 25):
    """
     Sliced Wasserstein distances between softmax vectors and the approx softmax vectors. 
     This time we do not normalize the approx softmax vectors and just treat them as vectors (locations) and an empirical measure on the vectors  (for now let us do uniform on the location)
    """
    #TODO Add other weights. 
    n_samples = source_dist.shape[0]
    a, b = np.ones((n_samples,)) / n_samples, np.ones((n_samples,)) / n_samples
    #TODO: FIX start and end of logspace
    n_projections_arr = np.logspace(0, 4, n_proj, dtype=int)
    res = np.empty((n_seed, 25))

    for seed in range(n_seed):
        for i, n_projections in enumerate(n_projections_arr):
            res[seed, i] = ot.sliced_wasserstein_distance(xs, xt, a, b, n_projections, seed)

    res_mean = np.mean(res, axis=0)
    res_std = np.std(res, axis=0)
    return res_mean, res_std

But when I call this function, I get the error message 
'''
AttributeError: module 'ot' has no attribute 'sliced_wasserstein_distance'
'''

**Comment by ncourty** [comment]
hi @arijitthegame. You need to import the function directly from `ot.sliced`, e.g.
`from ot.sliced import sliced_wasserstein_distance`
Please note also that in the branch 'backend' a new version of this function, with multiple backend support (numpy, Pytorch, Jax) will soon be available.

**Comment by arijitthegame** [comment]
Thank you.
