### ISSUE TITLE
How ot.emd would work with angle-based ground metrics from ot.dist?

### ISSUE THREAD

**Issue by oleg-kachan** [PythonOT/POT#283]
My question is whether OT supposed to work with angle-based ground metrics like cosine distance, correlation and covariance which all are listed in ot.dist API? -- https://pythonot.github.io/all.html?highlight=ot%20dist#ot.dist

Isn't OT supposed to work with non-negative ground metrics? How one can interpret negative values of ground metrics? Is it negative cost, thus incentive? Or, probably I should do some transformation of correlation for example taking values in [-1, 1] like taking its 1 minus absolute value, so transforming it to a range [0, 1] (0 - similar, 1 - dissimilar) to feed into ot.emd?

Thanks.

**Comment by rflamary** [comment]
Our OT solvers will work with any cost matrix you provide (even with negative value). For ot.emd, the optimal plan (not the value) is actually invariant when a constant is added to the cost matrix or if it is multiplied but a positive constant. For ot.sinkhorn it will have an effect but normalizing the cost matrix by dividing it with its maximum is a classical pre-processing step.

ot.dist is provided in POT as an easy to use function but you can use anything you want, the only constraint is that the cost matrix has the proper size.
