### ISSUE TITLE
POT doesn't build with poetry and Python 3.9

### ISSUE THREAD

**Issue by mbahri** [PythonOT/POT#285]
## Describe the bug
poetry add POT fails at build time due to missing build dependency "Cython"

I reported the bug to the poetry developers who diagnosed the issue: https://github.com/python-poetry/poetry/issues/4543#issuecomment-925158474

> these packages doesn't provide a wheel in all cases. So it's necessary to build them from the sdist files. The build step happens in a temporary build environment. That's why you don't have success by installing the build-dependency manually. All these package doesn't provide a pyproject.toml containing build-system requirements according to PEP 518. Please report it to the maintainer of the projects.

> It looks like POT provide wheel files for python < 3.9. So there is no need to build the package.

Would it be possible to specify the build-time requirements? Or alternatively wheels for Python 3.9?

Many thanks

**Comment by rflamary** [comment]
We are aware of this issue and are working on a proper pyproject.toml for the next release.

Note that we provide wheels for python 3.9 in the master branch that is very stable:
https://github.com/PythonOT/POT/runs/3634557814
download the artifacts

**Comment by rflamary** [comment]
Hello @mbahri 

Could you tell us if this is resolved since the release of POT 0.8 (that includes a pyproject.toml and also wheels for 3.9)? We will do a bug fix release shortly and we can have a look iff there is still a problem but we need some feedback.

**Comment by mbahri** [comment]
Hi @rflamary 

I've tested it on Linux with Python 3.9.9 and it worked.

Thanks for fixing this issue!

**Comment by rflamary** [comment]
awesome! I'm closing it then, thank you for teh feedback.
