### ISSUE TITLE
Remove rst compiled doc and notebooks from repository

### ISSUE THREAD

**Issue by rflamary** [PythonOT/POT#31]
The current documentation relies on sphinx-gallery which cannot be executed on readthedoc so we have to compile everything to rst and notebooks for a proper documentation.

This will make the repo explode so we should find a way to have an updated doc (staying on readthedoc if possible) probably by keeping a compiled version of the doc on a separate repository.

The compiled notebooks also are very nice (they allow a quick look at how the toolbox works) but should be stored also in a separate repo.

**Comment by agramfort** [comment]
FYI this script:

https://github.com/mne-tools/mne-python/blob/master/circle.yml

builds automatically

http://mne-tools.github.io/stable/index.html
