### ISSUE TITLE
sinkhorn converge issue in SinkhornL1l2Transport 

### ISSUE THREAD

**Issue by EnayatAria** [PythonOT/POT#314]
## Describe the bug

This bug is in a continuation of bug #311. 

When the regularization parameter 'reg'  is low I got UserWarning as "Sinkhorn did not converge". It suggests increasing the reg value. By increasing reg, there is no warning. However, the result of the first implementation is much better than the second one. 

### To Reproduce
use the datasets  already given in #311 

If you download the input files in C:\ , then the code is:

    import numpy as np
    import to

    Xs = np.loadtxt("C: / Xs.txt").reshape(604, 5)
    Xt = np.loadtxt("C: / Xt.txt").reshape(601, 5)
    ys = np.loadtxt("C: / ys.txt")

    ot_base = ot.da.SinkhornL1l2Transport(reg_e=10000, reg_cl=100, max_iter=100, verbose=True)
    ot_base.fit(Xs=Xs, ys=ys, Xt=Xt)
    transp_Xt_l1l2 = ot_base.inverse_transform(Xt=Xt)

### First result with reg_e=10000
it goes 7 iterations with the warning:

    It.  |Loss        |Relative loss|Absolute loss
    ------------------------------------------------
    0|5.193678e+06|0.000000e+00|0.000000e+00
    C:\Users\enayat.aria\PycharmProjects\pythonProject\venv\lib\site-packages\ot\bregman.py:517: UserWarning: Sinkhorn did not 
    converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
    warnings.warn("Sinkhorn did not converge. You might want to "
    1|3.150857e+05|1.548338e+01|4.878593e+06
    2|2.668430e+05|1.807908e-01|4.824275e+04
    3|2.663648e+05|1.795326e-03|4.782117e+02
    4|2.663600e+05|1.786680e-05|4.759001e+00
    5|2.663600e+05|1.312594e-07|3.496224e-02
    6|2.663598e+05|7.297142e-07|1.943665e-01
    7|2.663598e+05|0.000000e+00|0.000000e+00

A 2D scatter plot of the source data, target data and the target after the transformation is: 

![Figure_1](https://user-images.githubusercontent.com/46156951/143015920-4d409c25-d8b4-41df-9627-73e9b9c053bf.png)

### Second result with reg_e=1000000

When reg_e is 10^6, there is no sinkhorn coverage warning, and the code comes to an end after 5 iterations:
  
    It.  |Loss        |Relative loss|Absolute loss
    ------------------------------------------------
    0|-7.480469e+06|0.000000e+00|0.000000e+00
    1|-1.071924e+07|3.021455e-01|3.238770e+06
    2|-1.073195e+07|1.184767e-03|1.271486e+04
    3|-1.073200e+07|4.165733e-06|4.470665e+01
    4|-1.073200e+07|1.215266e-08|1.304224e-01
    5|-1.073200e+07|2.606419e-11|2.797209e-04

But the data distribution of the target after transport is not good at all:

![Figure_2](https://user-images.githubusercontent.com/46156951/143017506-71902cb7-fb71-466a-a70b-fa294b403188.png)

The second results give very inaccurate classification outcomes. 
Should I just consider the first implementation as a better outcome and not pay attention to the warning? (in this case, adding class information from the source dataset would not improve the final classification result, since I expected to have better classification than normal EMD ).  The second implementation gave even worse than the first one.  If there are other solutions, please let me know?

Thanks

**Comment by EnayatAria** [comment]
ot.da.SinkhornTransport also has the same problem!!

**Comment by rflamary** [comment]
You can change the value of  max_inner_iter that will give more iteration for the sinkhorn in the inner solver to converge instead of changing the regularization level.

In any case the behavior you are showing is not a bug but an effect of large entropic regularization that indeed does not work well in DA.

**Comment by EnayatAria** [comment]
Thanks for your help. It is working now without warning. 

I would suggest adding this comment to the warning message (bregman.py: 517) or modifying 'numItermax' to 'max_inner_iter' to avoid confusion.
