### ISSUE TITLE
dist function errors with a `callable` metric

### ISSUE THREAD

**Issue by zdk123** [PythonOT/POT#378]
## Describe the bug
According to the docstring of [ot.dist](https://github.com/PythonOT/POT/blob/master/ot/utils.py#L192-L216), the metric object can be be a callable function.

However, [L235](https://github.com/PythonOT/POT/blob/master/ot/utils.py#L235) clearly expects [only] a string.

Looks like this was broken in commit [0c5899](https://github.com/PythonOT/POT/commit/0c589912800b23609c730871c080ade0c807cdc1)
### To Reproduce
```py
import ot
import numpy as np

n = 10
a = np.random.randn(n,3)
b = np.random.randn(n,3)

eucl = lambda a, b: np.sum(np.square(a - b))
ot.dist(a, b, metric = eucl)
```
bug:
```
    if metric.endswith("minkowski"):
AttributeError: 'function' object has no attribute 'endswith'
```

Output of the following code snippet:
```python
import ot; print("POT", ot.__version__)
# POT 0.8.2
```

**Comment by rflamary** [comment]
Hello @zdk123 

Indeed this is a bug,  we should just test if metric is a string before with 
```if type(metric)==str and metric.endswith("minkowski"):```

Could you do a quick PR with this?

**Comment by zdk123** [comment]
sure!
