### ISSUE TITLE
Documentation build is failing

### ISSUE THREAD

**Issue by rflamary** [PythonOT/POT#403]
## Describe the bug

Documentation build is currently failing. For a while it was because of a too long example when using pytorch but in recent build (in PR) the following error has been reported on circleCI:

```
Sphinx-Gallery successfully executed 45 out of 47 files subselected by:

    gallery_conf["filename_pattern"] = '/plot'
    gallery_conf["ignore_pattern"]   = '__init__\\.py'

after excluding 0 files that had previously been run (based on MD5).


Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/circleci/project/examples/unbalanced-partial/plot_UOT_barycenter_1D.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/project/examples/unbalanced-partial/plot_UOT_barycenter_1D.py", line 130, in <module>
    ax = pl.gcf().gca(projection='3d')
TypeError: gca() got an unexpected keyword argument 'projection'


/home/circleci/project/examples/barycenters/plot_barycenter_1D.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/project/examples/barycenters/plot_barycenter_1D.py", line 109, in <module>
    ax = plt.gcf().gca(projection='3d')
TypeError: gca() got an unexpected keyword argument 'projection'
```

It seems to come from a use of matplotlib gca that is not possible anymore.

### To Reproduce

Build the documentation

### Expected behavior

Doc should build on circleCI and locally ;)

### Environment (please complete the following information):
CirclCI

**Comment by agramfort** [comment]
matplotlib update?

**Comment by rflamary** [comment]
I know @agramfort it's not a good practice, we did not fix the version in the requirement.txt, but it is usually pretty stable. They remove the parameter to`gca()` for 3d projection in 3.6 mid september...

**Comment by rflamary** [comment]
It was definitely a good way to detect problems for recent versions though

**Comment by rflamary** [comment]
that is what @ncassereau-idris did in his PR now everything works again
