### ISSUE TITLE
Wrong documentation in weak OT solver

### ISSUE THREAD

**Issue by jvlindheim** [PythonOT/POT#404]
Thanks for the addition of the weak OT solver this year!

I just wanted to comment on the docstring of this function. To my understanding, there is an error in the statement of the problem that is solved: The quadratic losses should be weighted by the source sample weights. Furthermore, there is a Latex error because of a missing space.
Finally, I would add G0 to the list of parameters.

**Comment by rflamary** [comment]
Hello @jvlindheim those arer all good points. Feel free to propose a PR to correct the documentation. This is good timing the weke OT solver has not been released officially yet.
