### ISSUE TITLE
Question regarding the usage of similarity/dissimilarity matrices in Fused Gromov Wasserstein distances

### ISSUE THREAD

**Issue by arijitthegame** [PythonOT/POT#405]
Thank you for the excellent repo. I am looking at the example of (Fused) GW Dictionary Learning : https://pythonot.github.io/auto_examples/gromov/plot_gromov_wasserstein_dictionary_learning.html#estimate-the-gromov-wasserstein-dictionary-from-the-dataset. In this example, the matrix C is a similarity matrix, namely the adjacency matrix and from the documentation, I should be able to use any similarity matrix. However, in the example of (fused) GW barycenters, https://pythonot.github.io/auto_examples/gromov/plot_gromov_barycenter.html, a dissimilarity, i.e. an Euclidean distance measure is used. I have the following two questions: 

1.  Can we use similarity matrices in the (fused) GW example? 
2.  Can one use a dissimilarity matrix for (Fused) GW dictionary learning? 
3.  If the answer to the above is no, can you please give some reasoning, intuition or even point me to the relevant literature why it is not possible? 

Thank you.

**Comment by rflamary** [comment]
You can use any symmetric matrix you want for both FGW and FGW dico ;). 

Just note that GW/FGW is a metric only when teh matrix is a disatnce. For adjacency matrix,  FGW is a dissimilarity measure that is not a metric but works bvery well in practice.

**Comment by arijitthegame** [comment]
Great. Thank you so much!!
