### ISSUE TITLE
Negative Gromov-Wasserstein distance

### ISSUE THREAD

**Issue by WenjunZHAOwO** [PythonOT/POT#406]
Hi,

Thank you for the extremely helpful software! Sometimes I encounter a negative value of gw_dist returned by gromov.entropic_gromov_wasserstein() function:

```
gw1, log1 = ot.gromov.entropic_gromov_wasserstein(
    C1, C2, p, q, 'square_loss', epsilon=0.01, log=True, verbose=True)
print(log1['gw_dist'])
```

However, from my understanding, the distance part has to be nonnegative given the square loss. Could you help me with my confusion? If helpful at all, my cost matrices are nonnegative, symmetric integer matrices of sizes 267*267 and 250*250, and the marginals p and q are uniform. The negative gw_dist value appears for epsilon=0.01, but not for epsilon=0.02 or 0.05. 

The version of packages is:

```
macOS-10.16-x86_64-i386-64bit
Python 3.8.8 (default, Apr 13 2021, 12:59:45) 
[Clang 10.0.0 ]
NumPy 1.20.1
SciPy 1.6.2
POT 0.8.1.0
```

**Comment by rflamary** [comment]
Hello, could you please uploda a working example of this (i is a bug GW should be positive indeed)?

Note that at the moement teh solver orks only for symmeric maroces C so if your graphs/marice sar asymmetric it might cuse a problem.

**Comment by WenjunZHAOwO** [comment]
Thank you for your reply, I really appreciate it. I created the zip file with C1 and C2 as distance matrices, and the notebook includes an example with negative distance. Please let me know if there is a better data format. 

[neg_dist.zip](https://github.com/PythonOT/POT/files/10032758/neg_dist.zip)


> Hello, could you please uploda a working example of this (i is a bug GW should be positive indeed)?
> 
> Note that at the moement teh solver orks only for symmeric maroces C so if your graphs/marice sar asymmetric it might cuse a problem.

**Comment by rflamary** [comment]
I can reprduce the negative distance. Will look into it but quite busy at the moement. We will try to handle this problem in PR #399 where we will work on the whole gromov pipeline

**Comment by WenjunZHAOwO** [comment]
> 

Thank you!

**Comment by tbng** [comment]
I remembered an update of POT about a year ago that fixed behaviours of the GW solvers by centering the gradients, not entirely sure it's related though https://twitter.com/rflamary/status/1517191890113904641

**Comment by rflamary** [comment]
this shomd be fixed now, from what I undrstand you have a negative gromov when the algorithm did not converge and violates the marginal onstraints. We now have a warning to that effect.
