### ISSUE TITLE
potential BUG in function utils.euclidean_distances()

### ISSUE THREAD

**Issue by lsj72123** [PythonOT/POT#430]
## Describe the bug

Hi, I am confused with the flag `squared=False` in the function utils.euclidean_distances().

According to the declaration, if `squared` flag is set to True, this function should return squared results. BUT in the code, it is not the case.

![image](https://user-images.githubusercontent.com/30463638/215671323-fdcbe698-bd75-412a-9c65-9e82267115e4.png)

why it takes square when this flag is `False`?

### Expected behavior

Do square operation when the argument 'squared' is set to `True`

### Environment (please complete the following information):

POT version: 0.8.2

Thank you!

**Comment by rflamary** [comment]
By default the function compute the euclidean distance (not squared) and that is why there is an sqrt (because the lines above, that are very fast, compute the squared euclidean distance). 

I don't think there is a bug here.

**Comment by lsj72123** [comment]
Yes, you're right, thanks for your reply.  The similar spelling of square and sqrt just misled me.
