### ISSUE TITLE
An Issue with solve_1d_linesearch_quad Function

### ISSUE THREAD

**Issue by Nuwaisir-1998** [PythonOT/POT#442]
I had this error: TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

After some observation, I found that inside `solve_1d_linesearch_quad` function in [optim.py](https://github.com/PythonOT/POT/blob/master/ot/optim.py), `np.divide` is used. I think it should be `nx.divide` where `nx = get_backend(a, b, c)`. And inside TorchBackend class, a new method for divide should be added that uses `torch.div` function.

**Comment by rflamary** [comment]
Hello @Nuwaisir-1998  very good point!

We are reworking all the optimization pipeline in PR #431  and I seem to recall that this has been corrected. @cedricvincentcuaz could you confirm that the PR correct this bug?

**Comment by cedricvincentcuaz** [comment]
Indeed this `np.divide` operation has been removed in PR #431  to prevent this kind of error. The minimum is now computed using only python operators as `minimum = min(1., max(0., -b / (2.0 * a)))` which inherits the type of `a` and `b`, whether there are 1D tensors or floats.
I do not think that a new method `nx.divide` is necessary in this function.

**Comment by Nuwaisir-1998** [comment]
Hi @cedricvincentcuaz,
I think you are correct, thanks!
