### ISSUE TITLE
Running Sphinx build error

### ISSUE THREAD

**Issue by x12hengyu** [PythonOT/POT#451]
## Describe the bug
We are trying to contribute a new feature called `DEMD` to POT. We have our code ready under `ot` folder and have two examples embedded under `examples/demd`. But when we start to run `make build` under `docs`, we keep getting error
```
* KeyError: 'ot'
* ModuleNotFoundError: No module named 'ot.lp.emd_wrap'
```
I'm wondering if anyone has similar issue or knows how to solve this. I really appreciate any help.
We also tried to manage packages under conda virtual environment to make all version and paths aligned. But it didn't work either. 

### To Reproduce
1. Please check my forked POT with new feature at [https://github.com/x12hengyu/POT/tree/demd](https://github.com/x12hengyu/POT/tree/demd)
2. `make build`, `make install` at root to build and install new package locally
3. `cd docs`, `make html` get error

#### Screenshots
<img width="1039" alt="Screen Shot 2023-04-04 at 17 04 47" src="https://user-images.githubusercontent.com/52917220/229933017-6c41c0a2-9514-4b5f-b6f6-6e1fa1d9b019.png">

#### Code sample

This is a build error.

### Expected behavior

Expected to build html documentation so we can verify our new code documentation.

### Environment (please complete the following information):
- OS: Linux
- Python version: 3.8
- How was POT installed (source, `pip`, `conda`): pip
- Build command you used (if compiling from source): `make build`, `make install`, `make html`
- Only for GPU related bugs:
    - CUDA version: N/A
    - GPU models and configuration: N/A
    - Any other relevant information: N/A

Output of the following code snippet:
```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import ot; print("POT", ot.__version__)
```
<img width="485" alt="Screen Shot 2023-04-04 at 17 23 04" src="https://user-images.githubusercontent.com/52917220/229935728-0fd54e3c-0463-4c74-85b7-51ebf8574480.png">

**Comment by rflamary** [comment]
Hello,

POT needs to be installed before  running the documentation which builds the C++ modules (ot.la.emd_wrap). make build is an old way to buil POT I recomend you do `pip install -e .`  in the POT folder instead

**Comment by x12hengyu** [comment]
Thank you so much, this works!
