### ISSUE TITLE
[FEAT] Split the huge "bregman.py" module

### ISSUE THREAD

**Issue by rflamary** [PythonOT/POT#567]
## 🚀 Feature

We need to split the dreaded bregman.py file in a proper module like we did for ot.gromov

the way I see that we can have 
```
bregman/
    __init__.py
    _sinkhorn.py
    _empirical.py
    _barycenter.py
    _convolutional.py
    _screenkhorn.py
```

This is mostly some maintenance with moving stuff and checking that all tests pass so I'm looking for a volunteers. This will help for future maintnance but we need to be carefull to put the good contriutor in the good sub module (their contribution should be in CONTRIBUTORS.md)

**Comment by cedricvincentcuaz** [comment]
I can go for it 👍
