### ISSUE TITLE
Upstream Licencing conflict with GPL: POT and CVXOPT

### ISSUE THREAD

**Issue by SarahG-579462** [PythonOT/POT#622]
## Describe the bug

POT uses MIT, but has a requirement for CVXOPT, which uses [GPLv3](https://cvxopt.org/copyright.html) (Likely because it uses [GLPK](https://en.wikipedia.org/wiki/GNU_Linear_Programming_Kit)). This means that any upstream code cannot use an incompatible license with GPL (e.g. Apache). 

### Additional context

This arose in the context of exploring the possibility of having POT as a requirement for [xclim](https://xclim.readthedocs.io/en/stable/). We can't downgrade our licenses due to branding issues, so as a result we cannot use POT without licensing violations.

https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l (specifically: [this answer](https://opensource.stackexchange.com/a/4557) suggests that until the CVXOPT is imported, POT is MIT, but after that, it is GPLv3.  )

**Comment by SarahG-579462** [comment]
An option for fixing this might be to dual-license POT, or making CVXOPT an optional requirement. It already seems to be optional in the codebase, given the try-catch on the import, but it is *not* in requirements.txt

**Comment by rflamary** [comment]
CVXOPTis already a optional requirement and run perfectly without it (albeit slower on some functions), it is in the requirement.txt but we are pkaning on making a requiremenat_all.txt with all optional dependencies. Optional depenencies are imported only if available so you can instal POT without CVXOPT and remain full MIT

**Comment by rflamary** [comment]
This Issue is solved by #627 so I'm closing it
